---
- name: configure base settings
  become: yes
  become_user: root
  block:

  - name: configure[base] - password for user root - change
    ansible.builtin.user:
      name: root
      password: "{{ base_server_root_password }}"
      expires: -1

  - name: configure[base] - cloud-init - disable
    ansible.builtin.copy:
      dest: '/etc/cloud/cloud-init.disabled'
      content: ''
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution == 'Ubuntu'

  - name: configure[base] - block device scheduler none - set
    ansible.builtin.copy:
      dest: /etc/udev/rules.d/60-scheduler.rules
      content: >
        ACTION=="add|change", KERNEL=="vd*[!0-9]|sr*", ATTR{queue/scheduler}="none"
      owner: root
      group: root
      mode: 0644
    notify:
      - trigger udevadm
    when:
      - ansible_virtualization_role == 'guest'
