---
# packages for base_server
- name: packages for {{ ansible_distribution }} host and guest systems
  become: yes
  become_user: root
  block:

  - name: install - remove unwanted packages - all systems
    ansible.builtin.apt:
      pkg:
        - accountsservice
        - alsa*
        - bolt
        - byobu
        - eatmydata
        - ftp
        # - libavahi*
        # - libcups2
        - lxd-agent-loader
        - man-db
        - manpages
        - ntp
        - overlayroot
        - packagekit
        - packagekit-tools
        - pastebinit
        - pinentry-gtk2
        - popularity-contest
        - procmail
        - snapd
        - sound-theme-freedesktop
        - squashfs-tools
        - ubuntu-advantage-tools
        - unattended-upgrades
        - update-manager-core
        - update-notifier-common
        - wamerican
      state: absent
      autoremove: yes
      purge: yes
      update_cache: no

  - name: install - remove unwanted packages - virtual systems
    ansible.builtin.apt:
      pkg:
        - irqbalance
        - fwupd
        - multipath-tools
        - powermgmt-base
        - thermald
      state: absent
      purge: yes
      update_cache: no
    when: ansible_virtualization_role == 'guest'

  - name: install - packages for HW host
    ansible.builtin.apt:
      pkg:
        - efitools
        - gpm
        - hdparm
        - intel-microcode
        - kpartx
        - lsscsi
        - nvme-cli
        - smartmontools
      state: present
      update_cache: yes
      install_recommends: no
    when: ansible_virtualization_role == 'host'

  - name: install - packages for VM guest
    ansible.builtin.apt:
      pkg:
        # - libvirt-clients
        - qemu-guest-agent
        # - vim
      state: present
      update_cache: yes
      install_recommends: no
    when: ansible_virtualization_role == 'guest'

  - name: install - packages - all systems
    ansible.builtin.apt:
      pkg:
        - openssh-server
        - openssh-client
        # - libpam-ssh-agent-auth
        - aptitude
        - apt-transport-https
        - bash-completion
        # - bridge-utils
        - bzip2
        - ca-certificates
        - chrony
        - colordiff
        - curl
        - diffstat
        - dnsutils
        - dosfstools
        - e2fsprogs
        - gnupg2
        - htop
        - iftop
        - iotop
        - less
        - mc
        - ncdu
        - net-tools
        - p7zip-full
        - patchutils
        - pciutils
        - psmisc
        - rsync
        - screen
        - sysstat
        - traceroute
        - tree
        - vim-tiny
        # - vim
        # - vlock
        - zip
      state: present
      update_cache: no
      install_recommends: no
