---
galaxy_info:
  author: operations@apollogames.com
  description: >
    Install and configure base Linux virtuals servers
  company: APOLLO SOFT, s.r.o.

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: CentOS Stream
    versions:
    - 8
  - name: OracleLinux
    versions:
    - 8
  - name: Ubuntu
    versions:
    - 20

  galaxy_tags: []

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
