---
hostname: sw2

# Parameters for connection type network_cli
ansible_ssh_user: admin
ansible_ssh_pass: tajneheslo
ansible_network_os: dellemc.os10.os10

#definice sytemovych promennych
os10_system:
  hostname: sw2

os10_ntp:
  source: mgmt 1/1/1
  server:
  - ip: 192.168.9.233
    state: present

#os10_vrf:
#  vrfdetails:
#  - vrf_name: EVPN
#    state: present

os10_interface:
  ethernet 1/1/9:
    desc: VLTi
    switchport: false
    admin: up
  range ethernet 1/1/1-1/1/8:
    desc: "pairs"
    switchport: False
    admin: up
  range ethernet 1/1/10-1/1/30:
    desc: "pairs"
    switchport: False
    admin: up

os_vlan:
  vlan 1000:
    description: "Management"
    state: present
  vlan 1001:
    description: "ILO"
    state: present
  vlan 1002:
    description: "VMOTION"
    state: present
  vlan 1003:
    description: "PubSim"
    state: present
  vlan 1008:
    description: "VMInternal"
    state: present
  range Po 1-30:
    switchport: true
    portmode: "trunk"
    admin: up

os10_lag:
  Po 1:
    type: dynamic
    min_links: 1
    lacp:
      long_timeout: true
      fast_switchover: true
    channel_members:
    - port: ethernet 1/1/1
      state: present
      mode: active
    state: present
  Po 2:
    type: dynamic
    min_links: 1
    lacp:
      long_timeout: true
      fast_switchover: true
    channel_members:
    - port: ethernet 1/1/2
      state: present
      mode: active
    state: present
  Po 3:
    type: dynamic
    min_links: 1
    lacp:
      long_timeout: true
      fast_switchover: true
    channel_members:
    - port: ethernet 1/1/3
      state: present
      mode: active
    state: present
  Po 4:
    type: dynamic
    min_links: 1
    lacp:
      long_timeout: true
      fast_switchover: true
    channel_members:
    - port: ethernet 1/1/4
      state: present
      mode: active
    state: present

# vytvoreni vlan 1000-1008,1100-1108
os10_vlan:
  vlan 1000:
    description: "MNGMT"
    ip_and_mask: "10.70.0.22/20"
    virtual_gateway_ip: "10.70.0.1"
    tagged_members:
      - port: po 1
        state: present
      - port: po 2
        state: present
      - port: po 3
        state: present
      - port: po 4
        state: present
      - port: po 5
        state: present
      - port: po 6
        state: present
    state: present
  vlan 1001:
    description: "ILO"
    tagged_members:
      - port: po 1
        state: present
      - port: po 2
        state: present
      - port: po 3
        state: present
      - port: po 4
        state: present
      - port: po 5
        state: present
      - port: po 6
        state: present
    state: present
  vlan 1002:
    description: "VMOTION"
    tagged_members:
      - port: po 1
        state: present
      - port: po 2
        state: present
      - port: po 3
        state: present
      - port: po 4
        state: present
      - port: po 5
        state: present
      - port: po 6
        state: present
    state: present
  vlan 1003:
    description: "PubSim"
    tagged_members:
      - port: po 1
        state: present
      - port: po 2
        state: present
      - port: po 3
        state: present
      - port: po 4
        state: present
      - port: po 5
        state: present
      - port: po 6
        state: present
    state: present
  vlan 1008:
    description: "VMInternal"
    tagged_members:
      - port: po 1
        state: present
      - port: po 2
        state: present
      - port: po 3
        state: present
      - port: po 4
        state: present
      - port: po 5
        state: present
      - port: po 6
        state: present
    state: present

#definice VLT domeny
os10_vlt:
  domain: 1
  backup_destination: "10.227.59.21"
  destination_type: "ipv4"
  discovery_intf: 1/1/9
  discovery_intf_state: present
  peer_routing: True
  vlt_peers:
    Po 1:
      peer_lag: 1
    Po 2:
      peer_lag: 2
    Po 3:
      peer_lag: 3
    Po 4:
      peer_lag: 4
    Po 5:
      peer_lag: 5
    Po 6:
      peer_lag: 6
